spring:
  datasource:
    #  url: jdbc:postgresql://localhost:5432/transneftpua_db
    #  username: postgres
    #  password: admin
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 1
      maximumPoolSize: 2
      dataSourceProperties:
        ApplicationName: "Microservice: ${spring.application.name} (${USERNAME})"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#  sql:
#    init:
#      mode: embedded  #script-based (data, schema) initialization is performed by default only for embedded databases
