spring:
  datasource:
#      url: jdbc:postgresql://localhost:5432/postgres
#      username: postgres
#      password: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver


  jpa:
    properties:
      hibernatc:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#   https://stackoverflow.com/questions/35411070/hibernate-not-creating-table-automatically-in-spring-boot-using-postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

#  sql:
#    init:
#      mode: embedded
