spring:
  h2.console.enabled: true
  datasource:
    # ImMemory
    url: jdbc:h2:mem:bootjava
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:bootjava
    # Absolute path
    #    url: jdbc:h2:C:/projects/bootjava/db/bootjava
    #    tcp: jdbc:h2:tcp://localhost:9092/C:/projects/bootjava/db/bootjava
    # Relative path form current dir
    #    url: jdbc:h2:./db/bootjava
    # Relative path from home
    #    url: jdbc:h2:~/bootjava
    #    tcp: jdbc:h2:tcp://localhost:9092/~/bootjava
    username: sa
    password:

  jpa:
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

