#spring:
#  datasource:
#    #  url: jdbc:postgresql://localhost:5432/transneftpua_db
#    #  username: postgres
#    #  password: admin
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:transneftpua_db}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASSWORD:admin}
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    properties:
#      hibernatc:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  sql:
#    init:
#      mode: embedded

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:transneftpua_db}
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    #      database: postgresql
    password: ${DB_PASSWORD:QAZwsx123}
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8080'