#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: postgres

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20

  # Jackson Serialization Issue Resolver
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none

  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
 # cache:
  #  cache-names: documents
   # caffeine.spec: maximumSize=5000,expireAfterAccess=60s

logging:
  level:
    root: WARN
    ru.sitronics.tn: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

s3RestService:
  url: ${S3_REST_SERVICE_URI:http://localhost:8081}
  postMultipartFilesEndpoint: ${POST_MP_FILES_ENDPOINT:/file}

rsql:
  defaultSort: ${DEFAULT_SORT:dateOfCreation,asc}
  defaultPageSize: ${DEFAULT_PAGE_SIZE:10}