spring:
  datasource:
    #  url: jdbc:postgresql://localhost:5432/transneftpua_db
    #  username: postgres
    #  password: admin
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:transneftpua_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 2

  jpa:
    properties:
      hibernatc:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: embedded
