spring:
  datasource:
    #  url: jdbc:postgresql://localhost:5432/transneftpua_db
    #  username: postgres
    #  password: admin
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATABASE:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 1
      maximumPoolSize: 2
      dataSourceProperties:
        ApplicationName: "Microservice: ${spring.application.name} (${USERNAME})"

  jpa:
    properties:
      hibernatc:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: none #с none нет автогенерации. Используем только data.sql и schema.sql.  https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
     # defer-datasource-initialization: true #гарантирует и автогерерацию, а после поикс изменний по schema и заполнение data
  sql:
    init:
      mode: embedded  #script-based (data, schema) initialization is performed by default only for embedded databases
